const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getVersions: () => ipcRenderer.invoke('get-versions'),
  getInstancesDir: () => ipcRenderer.invoke('get-instances-dir'),
  chooseInstanceLocation: () => ipcRenderer.invoke('choose-instance-location'),
  getLoaderVersions: (gameVersion, loader) => ipcRenderer.invoke('get-loader-versions', gameVersion, loader),
  createInstance: (data) => ipcRenderer.invoke('create-instance', data),
  listInstances: () => ipcRenderer.invoke('list-instances'),
  deleteInstance: (name) => ipcRenderer.invoke('delete-instance', name),
  updateInstance: (name, data) => ipcRenderer.invoke('update-instance', name, data),
  launchInstance: (name) => ipcRenderer.invoke('launch-instance', name),
  microsoftLogin: () => ipcRenderer.invoke('microsoft-login'),
  offlineLogin: (username) => ipcRenderer.invoke('offline-login', username),
  getAuth: () => ipcRenderer.invoke('get-auth'),
  listAccounts: () => ipcRenderer.invoke('list-accounts'),
  selectAccount: (key) => ipcRenderer.invoke('select-account', key),
  deleteAccount: (key) => ipcRenderer.invoke('delete-account', key),
  signOut: () => ipcRenderer.invoke('sign-out'),
  searchMods: (query, facets, offset, limit, sort) => ipcRenderer.invoke('search-mods', query, facets, offset, limit, sort),
  searchCurseForge: (query, options) => ipcRenderer.invoke('search-curseforge', query, options),
  getCurseForgeProject: (projectId) => ipcRenderer.invoke('get-curseforge-project', projectId),
  getCurseForgeFiles: (projectId, instanceName) => ipcRenderer.invoke('get-curseforge-files', projectId, instanceName),
  installCurseForgeContent: (instanceName, options) => ipcRenderer.invoke('install-curseforge-content', instanceName, options),
  getInstanceWorlds: (instanceName) => ipcRenderer.invoke('get-instance-worlds', instanceName),
  importCurseForgeModpack: (options) => ipcRenderer.invoke('import-curseforge-modpack', options),
  getProject: (projectId) => ipcRenderer.invoke('get-project', projectId),
  getProjectVersions: (projectId, loaders, gameVersions) => ipcRenderer.invoke('get-project-versions', projectId, loaders, gameVersions),
  installMod: (instanceName, options) => ipcRenderer.invoke('install-mod', instanceName, options),
  checkInstallFeasibility: (instanceName, projectId, versionId, loaders, gameVersion) => ipcRenderer.invoke('check-install-feasibility', instanceName, projectId, versionId, loaders, gameVersion),
  getOptionalDeps: (projectIds) => ipcRenderer.invoke('get-optional-deps', projectIds),
  getInstanceMods: (instanceName) => ipcRenderer.invoke('get-instance-mods', instanceName),
  getInstanceContent: (instanceName, type) => ipcRenderer.invoke('get-instance-content', instanceName, type),
  getRecentDestinations: () => ipcRenderer.invoke('get-recent-destinations'),
  getServerMetadata: (instanceName, address) => ipcRenderer.invoke('get-server-metadata', instanceName, address),
  removeRecentDestination: (instanceName, destination) => ipcRenderer.invoke('remove-recent-destination', instanceName, destination),
  renameRecentDestination: (instanceName, destination, name) => ipcRenderer.invoke('rename-recent-destination', instanceName, destination, name),
  launchDestination: (instanceName, destination) => ipcRenderer.invoke('launch-instance', instanceName, destination),
  removeInstanceContent: (instanceName, type, filename) => ipcRenderer.invoke('remove-instance-content', instanceName, type, filename),
  toggleInstanceContent: (instanceName, type, filename) => ipcRenderer.invoke('toggle-instance-content', instanceName, type, filename),
  removeMod: (instanceName, modId) => ipcRenderer.invoke('remove-mod', instanceName, modId),
  disableMod: (instanceName, filename) => ipcRenderer.invoke('disable-mod', instanceName, filename),
  checkModUpdates: (instanceName) => ipcRenderer.invoke('check-mod-updates', instanceName),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  checkJavaInstalled: () => ipcRenderer.invoke('check-java'),
  openJavaDownload: () => ipcRenderer.invoke('open-java-download'),
  copyText: (value) => ipcRenderer.invoke('copy-text', value),
  openInstanceFolder: (name) => ipcRenderer.invoke('open-instance-folder', name),
  getUpdateState: () => ipcRenderer.invoke('get-update-state'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),

  onUpdateState: (cb) => ipcRenderer.on('update-state', (_, value) => cb(value)),
  onLaunchProgress: (cb) => ipcRenderer.on('launch-progress', (_, v) => cb(v)),
  onLaunchData: (cb) => ipcRenderer.on('launch-data', (_, v) => cb(v)),
  onLaunchError: (cb) => ipcRenderer.on('launch-error', (_, v) => cb(v)),
  onLaunchClose: (cb) => ipcRenderer.on('launch-close', () => cb()),
  onLaunchLog: (cb) => ipcRenderer.on('launch-log', (_, v) => cb(v)),
  onLaunchMetrics: (cb) => ipcRenderer.on('launch-metrics', (_, v) => cb(v)),
  onLaunchFixed: (cb) => ipcRenderer.on('launch-fixed', (_, count) => cb(count)),
  onLaunchWarning: (cb) => ipcRenderer.on('launch-warning', (_, message) => cb(message)),
  onInstallProgress: (cb) => ipcRenderer.on('install-progress', (_, v) => cb(v)),
});
