const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getVersions: () => ipcRenderer.invoke('get-versions'),
  getInstancesDir: () => ipcRenderer.invoke('get-instances-dir'),
  chooseInstanceLocation: () => ipcRenderer.invoke('choose-instance-location'),
  getLoaderVersions: (gameVersion, loader) => ipcRenderer.invoke('get-loader-versions', gameVersion, loader),
  getNeoForgeStatus: (instanceName) => ipcRenderer.invoke('get-neoforge-status', instanceName),
  changeNeoForgeVersion: (instanceName, version) => ipcRenderer.invoke('change-neoforge-version', instanceName, version),
  repairNeoForge: (instanceName) => ipcRenderer.invoke('repair-neoforge', instanceName),
  rollbackNeoForge: (instanceName) => ipcRenderer.invoke('rollback-neoforge', instanceName),
  createInstance: (data) => ipcRenderer.invoke('create-instance', data),
  duplicateInstance: (name, options) => ipcRenderer.invoke('duplicate-instance', name, options),
  cancelTransfer: (operationId) => ipcRenderer.invoke('cancel-transfer', operationId),
  bulkUpdateInstances: (names, action) => ipcRenderer.invoke('bulk-update-instances', names, action),
  bulkDeleteInstances: (names) => ipcRenderer.invoke('bulk-delete-instances', names),
  exportInstance: (name, options) => ipcRenderer.invoke('export-instance', name, options),
  chooseInstanceImport: () => ipcRenderer.invoke('choose-instance-import'),
  importPineArchive: (options) => ipcRenderer.invoke('import-pine-archive', options),
  importPineManifest: (options) => ipcRenderer.invoke('import-pine-manifest', options),
  importModrinthArchive: (options) => ipcRenderer.invoke('import-modrinth-archive', options),
  installModrinthModpack: (options) => ipcRenderer.invoke('install-modrinth-modpack', options),
  chooseExistingInstanceFolder: () => ipcRenderer.invoke('choose-existing-instance-folder'),
  getKnownLauncherFolders: () => ipcRenderer.invoke('get-known-launcher-folders'),
  scanKnownLauncherFolders: (keys) => ipcRenderer.invoke('scan-known-launcher-folders', keys),
  importExistingInstanceFolder: (options) => ipcRenderer.invoke('import-existing-instance-folder', options),
  repairManagedPack: (name) => ipcRenderer.invoke('repair-managed-pack', name),
  getManagedPackStatus: (name) => ipcRenderer.invoke('get-managed-pack-status', name),
  changeManagedPackVersion: (name, versionId) => ipcRenderer.invoke('change-managed-pack-version', name, versionId),
  rollbackManagedPack: (name) => ipcRenderer.invoke('rollback-managed-pack', name),
  listInstances: () => ipcRenderer.invoke('list-instances'),
  listGroups: () => ipcRenderer.invoke('list-groups'),
  createGroup: (name) => ipcRenderer.invoke('create-group', name),
  deleteGroup: (name) => ipcRenderer.invoke('delete-group', name),
  deleteInstance: (name) => ipcRenderer.invoke('delete-instance', name),
  updateInstance: (name, data) => ipcRenderer.invoke('update-instance', name, data),
  listInstanceBackups: (name) => ipcRenderer.invoke('list-instance-backups', name),
  createInstanceBackup: (name, options) => ipcRenderer.invoke('create-instance-backup', name, options),
  restoreInstanceBackup: (name, id, confirmedNewerWorlds) => ipcRenderer.invoke('restore-instance-backup', name, id, confirmedNewerWorlds),
  deleteInstanceBackup: (name, id) => ipcRenderer.invoke('delete-instance-backup', name, id),
  setInstanceBackupRetention: (name, value) => ipcRenderer.invoke('set-instance-backup-retention', name, value),
  launchInstance: (name) => ipcRenderer.invoke('launch-instance', name),
  microsoftLogin: (options) => ipcRenderer.invoke('microsoft-login', options),
  offlineLogin: (username) => ipcRenderer.invoke('offline-login', username),
  getAuth: () => ipcRenderer.invoke('get-auth'),
  listAccounts: () => ipcRenderer.invoke('list-accounts'),
  selectAccount: (key) => ipcRenderer.invoke('select-account', key),
  deleteAccount: (key) => ipcRenderer.invoke('delete-account', key),
  signOut: () => ipcRenderer.invoke('sign-out'),
  searchMods: (query, facets, offset, limit, sort) => ipcRenderer.invoke('search-mods', query, facets, offset, limit, sort),
  searchCurseForge: (query, options) => ipcRenderer.invoke('search-curseforge', query, options),
  getCurseForgeProject: (projectId) => ipcRenderer.invoke('get-curseforge-project', projectId),
  getCurseForgeFiles: (projectId, instanceName) => ipcRenderer.invoke('get-curseforge-files', projectId, instanceName),
  installCurseForgeContent: (instanceName, options) => ipcRenderer.invoke('install-curseforge-content', instanceName, options),
  getInstanceWorlds: (instanceName) => ipcRenderer.invoke('get-instance-worlds', instanceName),
  getInstanceWorldDetails: (instanceName) => ipcRenderer.invoke('get-instance-world-details', instanceName),
  getWorldLaunchRisk: (instanceName, identifier) => ipcRenderer.invoke('get-world-launch-risk', instanceName, identifier),
  renameWorld: (instanceName, identifier, name) => ipcRenderer.invoke('rename-world', instanceName, identifier, name),
  installWorldDatapackFile: (instanceName, identifier) => ipcRenderer.invoke('install-world-datapack-file', instanceName, identifier),
  installModrinthDatapack: (instanceName, identifier, projectId) => ipcRenderer.invoke('install-modrinth-datapack', instanceName, identifier, projectId),
  openInstanceScreenshots: (instanceName) => ipcRenderer.invoke('open-instance-screenshots', instanceName),
  duplicateWorld: (instanceName, identifier) => ipcRenderer.invoke('duplicate-world', instanceName, identifier),
  deleteWorld: (instanceName, identifier) => ipcRenderer.invoke('delete-world', instanceName, identifier),
  openWorldFolder: (instanceName, identifier) => ipcRenderer.invoke('open-world-folder', instanceName, identifier),
  exportWorld: (instanceName, identifier) => ipcRenderer.invoke('export-world', instanceName, identifier),
  importCurseForgeModpack: (options) => ipcRenderer.invoke('import-curseforge-modpack', options),
  getProject: (projectId) => ipcRenderer.invoke('get-project', projectId),
  getProjectVersions: (projectId, loaders, gameVersions) => ipcRenderer.invoke('get-project-versions', projectId, loaders, gameVersions),
  checkPerformancePreset: (gameVersion) => ipcRenderer.invoke('check-performance-preset', gameVersion),
  installMod: (instanceName, options) => ipcRenderer.invoke('install-mod', instanceName, options),
  checkInstallFeasibility: (instanceName, projectId, versionId, loaders, gameVersion) => ipcRenderer.invoke('check-install-feasibility', instanceName, projectId, versionId, loaders, gameVersion),
  getOptionalDeps: (projectIds) => ipcRenderer.invoke('get-optional-deps', projectIds),
  getInstanceMods: (instanceName) => ipcRenderer.invoke('get-instance-mods', instanceName),
  getInstanceContent: (instanceName, type) => ipcRenderer.invoke('get-instance-content', instanceName, type),
  getRecentDestinations: () => ipcRenderer.invoke('get-recent-destinations'),
  getServerMetadata: (instanceName, address) => ipcRenderer.invoke('get-server-metadata', instanceName, address),
  removeRecentDestination: (instanceName, destination) => ipcRenderer.invoke('remove-recent-destination', instanceName, destination),
  renameRecentDestination: (instanceName, destination, name) => ipcRenderer.invoke('rename-recent-destination', instanceName, destination, name),
  launchDestination: (instanceName, destination) => ipcRenderer.invoke('launch-instance', instanceName, destination),
  removeInstanceContent: (instanceName, type, filename) => ipcRenderer.invoke('remove-instance-content', instanceName, type, filename),
  toggleInstanceContent: (instanceName, type, filename) => ipcRenderer.invoke('toggle-instance-content', instanceName, type, filename),
  removeMod: (instanceName, modId) => ipcRenderer.invoke('remove-mod', instanceName, modId),
  disableMod: (instanceName, filename) => ipcRenderer.invoke('disable-mod', instanceName, filename),
  checkModUpdates: (instanceName) => ipcRenderer.invoke('check-mod-updates', instanceName),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getStorageUsage: () => ipcRenderer.invoke('get-storage-usage'),
  clearDownloadCache: (confirmed) => ipcRenderer.invoke('clear-download-cache', confirmed),
  checkJavaInstalled: () => ipcRenderer.invoke('check-java'),
  openJavaDownload: () => ipcRenderer.invoke('open-java-download'),
  copyText: (value) => ipcRenderer.invoke('copy-text', value),
  analyzeCrash: (instanceName, log) => ipcRenderer.invoke('analyze-crash', instanceName, log),
  uploadCrashLog: (instanceName, log, confirmed) => ipcRenderer.invoke('upload-crash-log', instanceName, log, confirmed),
  openSupportLog: (url) => ipcRenderer.invoke('open-support-log', url),
  repairInstanceFiles: (instanceName) => ipcRenderer.invoke('repair-instance-files', instanceName),
  getGameStatus: () => ipcRenderer.invoke('get-game-status'),
  terminateGame: (instanceName, confirmed) => ipcRenderer.invoke('terminate-game', instanceName, confirmed),
  openInstanceFolder: (name) => ipcRenderer.invoke('open-instance-folder', name),
  getUpdateState: () => ipcRenderer.invoke('get-update-state'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  openUpdateDownload: (url) => ipcRenderer.invoke('open-update-download', url),

  onUpdateState: (cb) => ipcRenderer.on('update-state', (_, value) => cb(value)),
  onLaunchProgress: (cb) => ipcRenderer.on('launch-progress', (_, v) => cb(v)),
  onLaunchData: (cb) => ipcRenderer.on('launch-data', (_, v) => cb(v)),
  onLaunchError: (cb) => ipcRenderer.on('launch-error', (_, v) => cb(v)),
  onLaunchClose: (cb) => ipcRenderer.on('launch-close', () => cb()),
  onLaunchLog: (cb) => ipcRenderer.on('launch-log', (_, v) => cb(v)),
  onLaunchMetrics: (cb) => ipcRenderer.on('launch-metrics', (_, v) => cb(v)),
  onLaunchFixed: (cb) => ipcRenderer.on('launch-fixed', (_, count) => cb(count)),
  onLaunchWarning: (cb) => ipcRenderer.on('launch-warning', (_, message) => cb(message)),
  onJavaInstallProgress: (cb) => ipcRenderer.on('java-install-progress', (_, value) => cb(value)),
  onInstallProgress: (cb) => ipcRenderer.on('install-progress', (_, v) => cb(v)),
  onDuplicateProgress: (cb) => ipcRenderer.on('duplicate-progress', (_, v) => cb(v)),
  onImportProgress: (cb) => ipcRenderer.on('import-progress', (_, v) => cb(v)),
});
